/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NoteSynthesizerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  apiEndpoint: "https://api.anthropic.com/v1/messages",
  modelName: "claude-3-5-sonnet-20241022",
  apiKey: "",
  summaryLength: "medium"
};

// src/settings.ts
var import_obsidian = require("obsidian");
var NoteSynthesizerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Note Synthesizer Settings" });
    new import_obsidian.Setting(containerEl).setName("API Endpoint").setDesc("The API endpoint URL for synthesis requests").addText(
      (text) => text.setPlaceholder("https://api.anthropic.com/v1/messages").setValue(this.plugin.settings.apiEndpoint).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.apiEndpoint = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Model Name").setDesc("The AI model to use for synthesis").addText(
      (text) => text.setPlaceholder("claude-3-5-sonnet-20241022").setValue(this.plugin.settings.modelName).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.modelName = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("Your API key (stored securely by Obsidian)").addText(
      (text) => text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.apiKey).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.apiKey = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Summary Length").setDesc("Choose the length of the synthesized summary").addDropdown(
      (dropdown) => dropdown.addOption("brief", "Brief (2-3 paragraphs)").addOption("medium", "Medium (1-2 pages)").addOption("comprehensive", "Comprehensive").setValue(this.plugin.settings.summaryLength).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.summaryLength = value;
        yield this.plugin.saveSettings();
      }))
    );
  }
};

// src/synthesize-modal.ts
var import_obsidian2 = require("obsidian");
var SynthesizeModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.selectedFiles = /* @__PURE__ */ new Set();
    this.synthesizeBtn = null;
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Synthesize Notes" });
    contentEl.createEl("p", { text: "Select 2 or more files to synthesize:" });
    const markdownFiles = this.app.vault.getMarkdownFiles();
    if (markdownFiles.length === 0) {
      contentEl.createEl("p", {
        text: "No markdown files found in vault.",
        cls: "note-synthesizer-warning"
      });
      return;
    }
    const fileListEl = contentEl.createDiv("note-synthesizer-file-list");
    fileListEl.style.maxHeight = "300px";
    fileListEl.style.overflowY = "auto";
    fileListEl.style.border = "1px solid var(--background-secondary-alt)";
    fileListEl.style.padding = "10px";
    fileListEl.style.marginBottom = "15px";
    markdownFiles.forEach((file) => {
      const fileItemEl = fileListEl.createDiv("note-synthesizer-file-item");
      fileItemEl.style.display = "flex";
      fileItemEl.style.alignItems = "center";
      fileItemEl.style.padding = "5px 0";
      const checkbox = fileItemEl.createEl("input", {
        type: "checkbox",
        attr: { id: `file-${file.path}` }
      });
      checkbox.style.marginRight = "10px";
      const label = fileItemEl.createEl("label", {
        text: file.name,
        attr: { htmlFor: `file-${file.path}` }
      });
      label.style.cursor = "pointer";
      label.style.flex = "1";
      checkbox.addEventListener("change", (e) => {
        if (e.target.checked) {
          this.selectedFiles.add(file);
        } else {
          this.selectedFiles.delete(file);
        }
        this.updateSynthesizeButton();
      });
    });
    const buttonContainerEl = contentEl.createDiv("note-synthesizer-buttons");
    buttonContainerEl.style.display = "flex";
    buttonContainerEl.style.gap = "10px";
    buttonContainerEl.style.justifyContent = "flex-end";
    this.synthesizeBtn = new import_obsidian2.ButtonComponent(buttonContainerEl).setButtonText("Synthesize").onClick(() => __async(this, null, function* () {
      if (this.selectedFiles.size < 2) {
        return;
      }
      const files = Array.from(this.selectedFiles);
      this.close();
      yield this.plugin.runSynthesis(files);
    }));
    new import_obsidian2.ButtonComponent(buttonContainerEl).setButtonText("Cancel").onClick(() => {
      this.close();
    });
    this.updateSynthesizeButton();
  }
  updateSynthesizeButton() {
    if (this.synthesizeBtn) {
      this.synthesizeBtn.setDisabled(this.selectedFiles.size < 2);
    }
  }
};
var ErrorModal = class _ErrorModal extends import_obsidian2.Modal {
  constructor(app, message, onRetry) {
    super(app);
    this.onRetry = null;
    this.message = message;
    this.onRetry = onRetry || null;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Synthesis Error" });
    contentEl.createEl("p", { text: this.message });
    const buttonContainerEl = contentEl.createDiv("note-synthesizer-buttons");
    buttonContainerEl.style.display = "flex";
    buttonContainerEl.style.gap = "10px";
    buttonContainerEl.style.justifyContent = "flex-end";
    buttonContainerEl.style.marginTop = "20px";
    if (this.onRetry) {
      new import_obsidian2.ButtonComponent(buttonContainerEl).setButtonText("Retry").onClick(() => __async(this, null, function* () {
        this.close();
        try {
          yield this.onRetry();
        } catch (error) {
          const errorMsg = error instanceof Error ? error.message : "Unknown error";
          new _ErrorModal(this.app, errorMsg, this.onRetry).open();
        }
      }));
    }
    new import_obsidian2.ButtonComponent(buttonContainerEl).setButtonText("Close").onClick(() => {
      this.close();
    });
  }
};

// src/api-client.ts
var import_obsidian3 = require("obsidian");
function sendToApi(endpoint, apiKey, model, systemPrompt, userContent) {
  return __async(this, null, function* () {
    var _a;
    if (!apiKey) {
      throw new Error("API key is not configured. Please set it in plugin settings.");
    }
    const request = {
      model,
      max_tokens: 4096,
      system: systemPrompt,
      messages: [
        {
          role: "user",
          content: userContent
        }
      ]
    };
    try {
      const response = yield (0, import_obsidian3.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01",
          "content-type": "application/json"
        },
        contentType: "application/json",
        body: JSON.stringify(request)
      });
      if (response.status !== 200) {
        let errorMessage = `API Error: ${response.status}`;
        try {
          const errorData = response.json;
          if ((_a = errorData == null ? void 0 : errorData.error) == null ? void 0 : _a.message) {
            errorMessage = `API Error: ${errorData.error.message}`;
          }
        } catch (e) {
        }
        throw new Error(errorMessage);
      }
      const data = response.json;
      if (!data.content || data.content.length === 0) {
        throw new Error("Empty response from API");
      }
      return data.content[0].text;
    } catch (error) {
      if (error instanceof Error) {
        throw error;
      }
      throw new Error("Failed to connect to API endpoint");
    }
  });
}

// src/main.ts
var NoteSynthesizerPlugin = class extends import_obsidian4.Plugin {
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addSettingTab(new NoteSynthesizerSettingTab(this.app, this));
      this.addCommand({
        id: "synthesize-notes",
        name: "Synthesize Notes",
        callback: () => {
          if (!this.settings.apiKey) {
            new import_obsidian4.Notice("API key not configured. Open Settings and configure the API key.");
            return;
          }
          new SynthesizeModal(this.app, this).open();
        }
      });
      console.log("Note Synthesizer plugin loaded");
    });
  }
  onunload() {
    return __async(this, null, function* () {
      console.log("Note Synthesizer plugin unloaded");
    });
  }
  loadSettings() {
    return __async(this, null, function* () {
      const data = yield this.loadData();
      this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
  runSynthesis(files) {
    return __async(this, null, function* () {
      const fileNames = files.map((f) => f.name).join(", ");
      try {
        new import_obsidian4.Notice(`Synthesizing ${files.length} notes...`);
        const fileContents = [];
        for (const file of files) {
          try {
            const content = yield this.app.vault.read(file);
            fileContents.push(`--- File: ${file.name} ---
${content}`);
          } catch (error) {
            console.warn(`Failed to read file ${file.name}:`, error);
            new import_obsidian4.Notice(`Warning: Could not read ${file.name}, skipping...`);
          }
        }
        if (fileContents.length === 0) {
          new import_obsidian4.Notice("No files could be read. Synthesis cancelled.");
          return;
        }
        const userContent = fileContents.join("\n\n");
        const systemPrompt = this.buildSystemPrompt(this.settings.summaryLength);
        const synthesis = yield sendToApi(
          this.settings.apiEndpoint,
          this.settings.apiKey,
          this.settings.modelName,
          systemPrompt,
          userContent
        );
        const timestamp = this.getTimestamp();
        const outputFileName = `Synthesis_${timestamp}.md`;
        const outputContent = `# Synthesis: ${fileNames}

${synthesis}`;
        const newFile = yield this.app.vault.create(outputFileName, outputContent);
        yield this.app.workspace.getLeaf().openFile(newFile);
        new import_obsidian4.Notice(`Synthesis complete: ${outputFileName}`);
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : "Unknown error occurred";
        new ErrorModal(this.app, errorMsg, () => this.runSynthesis(files)).open();
      }
    });
  }
  buildSystemPrompt(length) {
    const basePrompt = "You are a document analyst. Synthesize these sources by: 1) Identifying overlapping sections and merging them, 2) Highlighting unique insights from each source. Output as a structured document.";
    const lengthGuidance = {
      brief: "Produce a brief synthesis of 2\u20133 paragraphs.",
      medium: "Produce a medium-length synthesis of 1\u20132 pages.",
      comprehensive: "Produce a comprehensive synthesis covering all key points in depth."
    };
    return `${basePrompt}

${lengthGuidance[length]}`;
  }
  getTimestamp() {
    const now = /* @__PURE__ */ new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, "0");
    const day = String(now.getDate()).padStart(2, "0");
    const hours = String(now.getHours()).padStart(2, "0");
    const minutes = String(now.getMinutes()).padStart(2, "0");
    const seconds = String(now.getSeconds()).padStart(2, "0");
    return `${year}-${month}-${day}_${hours}-${minutes}-${seconds}`;
  }
};
